//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.WebForms
{
    public partial class SqlQueries
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblTimestamp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTimestamp;

        /// <summary>
        /// lblQueryCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblQueryCount;

        /// <summary>
        /// lblTotalTime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalTime;

        /// <summary>
        /// lblTotalEmployees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalEmployees;

        /// <summary>
        /// lblTotalTasks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalTasks;

        /// <summary>
        /// lblOverdueTasks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOverdueTasks;

        /// <summary>
        /// lblRecentComments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRecentComments;

        /// <summary>
        /// lblEmployeeError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmployeeError;

        /// <summary>
        /// gvEmployees control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvEmployees;

        /// <summary>
        /// lblTaskError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTaskError;

        /// <summary>
        /// gvTasks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvTasks;

        /// <summary>
        /// lblStatusError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatusError;

        /// <summary>
        /// rptStatusCounts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptStatusCounts;

        /// <summary>
        /// lblAuditError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAuditError;

        /// <summary>
        /// gvAuditLogs control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvAuditLogs;

        /// <summary>
        /// lblOverdueError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOverdueError;

        /// <summary>
        /// gvOverdueTasks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOverdueTasks;

        /// <summary>
        /// lblDeptError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDeptError;

        /// <summary>
        /// gvDepartmentWorkload control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvDepartmentWorkload;

        /// <summary>
        /// lblDeptSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblDeptSummary;

        /// <summary>
        /// lblCommentError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCommentError;

        /// <summary>
        /// gvComments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvComments;
    }
}
